# Bài tập 1: Xây dựng mảng các luỹ thừa của 2 nhỏ hơn 1025, bao gồm cả 1 = 2**0. Gợi ý: Nếu a là một mảng và b là một số thì b**a sẽ trả về một mảng cùng kích thước với a mà phần tử có chỉ số i bằng b**a[i], với ** là toán tử luỹ thừa.

# Bài tập 2: Xây dựng mảng gồm 10 phần tử, trong đó 9 phần tử đầu bằng 3, phần tử cuối cùng bằng 1.5.



In [3]:
import numpy as np 
# Ex 1. 
# TODO: create an array comprising of all power of 2 and < 1025, 
# including 1 = 2** 0, store result in x  
x =2**np.arange(0,np.log2(1025),1,dtype = int)
# -- end TODO ---

# Ex 2.
# TODO: create an array of 10 elements, all of them = 3 except the last one = 1.5, 
# store result in y 
y=3*np.ones(10)
#y[0:8]=3
y[9]=1.5
# -- end TODO ----

print(x, y)

[   1    2    4    8   16   32   64  128  256  512 1024] [3.  3.  3.  3.  3.  3.  3.  3.  3.  1.5]


In [4]:
x = np.array([3, 4, 5])

In [5]:
d = x.shape[0]

In [6]:
d

3

Trong Python có một điểm đặc biệt là Chỉ số ngược. Cho một mảng 1 chiều x có d phần tử. Để truy cập vào phần tử cuối cùng của mảng này, không cần biết d là bao nhiêu, ta có thể dùng chỉ số -1.

Bài tập: Thay toàn bộ các phần tử của mảng bằng trung bình cộng các phần tử trong mảng đó, sử dụng vòng for. Hàm này không trả về biến nào mà chỉ thay đổi các giá trị của biến đầu vào x.

In [15]:
import numpy as np 

def myavg(x):
    """
    :type x: a 1d array
    :rtype: None
    """
    # number of elements in x 
    d = x.shape[0]
    # create a variable to store sum of all elements
    res = 0 
    for i in range(d):
      # TODO: add the i-th element of x to res
      res +=x[i]
      # -- end TODO --
    # take average
    print(res)
    print(d)
    m = res/d
    # assign this new value to every element of x
    for i in range(d):
      # TODO: assign m to every element of x 
      x[i]=m
      # -- end TODO -- 
    

# create a 1d array
x = np.array([1., 2, 3, 4, 5, 6, 7, 8, 9, 10])
myavg(x)
print(x)

55.0
10
[5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5 5.5]


Bài tập: Cho một mảng 1 chiều x, tính mảng y và z sao cho y[i] = pi/2 - x[i] và z[i] = cos(x[i]) - sin(x[i]). Sau đó trả về tổng các phần tử của z

Viết hàm số tính tổng trị tuyệt đối các phần tử của một mảng một chiều. (Gợi ý: np.abs.)

In [17]:
import numpy as np 

def mynorm1(x):
  res = 0
  ## TODO
  for i in range(x.shape[0]):
    res +=np.abs(x[i])
  
  ## -- end TODO-- 
  return res
 
np.random.seed(1)
x = np.random.randn(1000)
print("{:.4f}".format(mynorm1(x)))

777.2455


Bài tập: Hãy lập trình hàm softmax.

$$a_i=\frac{exp(z_i)}{\sum_{j=0}^{d-1} exp(z_i) }$$

với $$exp(u)=e^u$$

In [46]:
np.random.seed(1) 
z = np.random.randn(10)

In [47]:
sum=np.sum(np.exp(z))

In [51]:
a = np.zeros_like(z)
a=np.exp(z)/sum
print(a)

[0.29213776 0.03122202 0.03394387 0.01968607 0.13676823 0.00576233
 0.32953807 0.02688782 0.07919548 0.04485835]


Bài tập: Tính norm 2 của một vector - vector này được biểu diễn dưới dạng mảng numpy một chiều.Norm 2 của một vector 
x,được ký hiệu là $||x||_2$ được định nghĩa là căn bậc hai của tổng bình phương các phần tử của nó.

$$||x||_2=\sqrt{x_0^2 + x_1^2+.... +x_{d-1}^2}$$ 

In [26]:
np.random.seed(1)
x = np.random.randn(10000)

In [32]:
np.linalg.norm(x,ord=None, axis=None, keepdims=False)

99.88336530026436

argmin, argmax
Để tìm chỉ số mà tại đó mảng một chiều đạt giá trị nhỏ nhất hay lớn nhất, ta có thể sử dụng np.argmin, hoặc np.argmax:

Bài tập: Trong bài toán classification, sử dụng Softmax Regression, giả sử ta đã tính được xác suất để một điểm dữ liệu thuộc vào mỗi class. Các xác suất này được lưu dưới dạng một mảng một chiều mà phần tử thứ i là xác suất để điểm dữ liệu rơi vào lớp i. Nhãn của dữ liệu được dự đoán là chỉ số của lớp mà điểm dữ liệu rơi vào với xác suất cao nhất. Hãy viết một hàm số xác định chỉ số đó.

Chú ý: Mảng chứa xác suất này thường được tính bằng cách áp dụng hàm softmax vào score vector. Hàm softmax giữ nguyên thứ tự của vector đầu vào, vì vậy chỉ số của lớp có xác suất cao nhất cũng là chỉ số của lớp có score cao nhất. (Mời bạn đọc thêm bài Softmax Regression để biết thêm chi tiết).

In [37]:
np.random.seed(1)
# suppose that there are 1000 classes
score = np.random.randn(1000) 
res = -1
## TODO 
sm = np.exp(score)/np.exp(score).sum(axis = 0)
res = sm.argmax()
## -- end TODO --
print(res)

565


![soft_max](soft_max.png)

In [40]:
np.random.seed(1) 
z = np.random.randn(3)+1000
sum=np.sum(np.exp(z)-np.max(z))
a = np.zeros_like(z)
for i in range(np.shape(z)[0]):
   a[i] += np.exp(z[i]-np.max(z)) / sum

In [41]:
a

array([0.29213776, 0.03122202, 0.03394387, 0.01968607, 0.13676823,
       0.00576233, 0.32953807, 0.02688782, 0.07919548, 0.04485835])

In [44]:
np.random.seed(2) 
z = np.random.randn(3)+1000
sum=np.sum(np.exp(z))
a = np.zeros_like(z)
for i in range(np.shape(z)[0]):
   a[i] += np.exp(z[i]) / sum

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in double_scalars
  
