In [1]:
import numpy as np

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
data =np.random.randint(0,100,(10,2))

In [10]:
data

array([[67, 78],
       [55, 89],
       [49, 55],
       [17, 85],
       [65, 67],
       [25, 79],
       [56, 26],
       [74, 99],
       [15,  2],
       [11, 73]])

In [11]:
scaler_model=MinMaxScaler()


In [12]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [14]:
scaler_model.fit(data)
#Tim hieu gia trị tối thiểu và tối đa của mỗi cột

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [17]:
scaler_model.transform(data)
#Chuyển đổi dữ liệu giá trị tối thiểu sẽ bằng 0

array([[0.88888889, 0.78350515],
       [0.6984127 , 0.89690722],
       [0.6031746 , 0.54639175],
       [0.0952381 , 0.8556701 ],
       [0.85714286, 0.67010309],
       [0.22222222, 0.79381443],
       [0.71428571, 0.24742268],
       [1.        , 1.        ],
       [0.06349206, 0.        ],
       [0.        , 0.73195876]])

In [18]:
scaler_model.fit_transform(data)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.88888889, 0.78350515],
       [0.6984127 , 0.89690722],
       [0.6031746 , 0.54639175],
       [0.0952381 , 0.8556701 ],
       [0.85714286, 0.67010309],
       [0.22222222, 0.79381443],
       [0.71428571, 0.24742268],
       [1.        , 1.        ],
       [0.06349206, 0.        ],
       [0.        , 0.73195876]])

In [25]:
import pandas as pd

my_data=np.random.randint(0,100,(10,3))


In [28]:
data =pd.DataFrame(data=my_data,columns=['f1','f2','f3'])

In [29]:
data

f1  f2  f3
0  80  50  27
1  50  35  70
2   6  85  69
3   3  63  46
4   5  42  29
5  25  20   2
6  67  43  22
7  49  94  53
8  41  33  10
9  67  36   5

In [35]:
X=data[['f1','f2']]
y=data['f3']

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=101)

In [40]:
x_train.shape
x_train

f1  f2
0  80  50
4   5  42
9  67  36
3   3  63
5  25  20
7  49  94
6  67  43
1  50  35

In [39]:
x_test.shape

(2, 2)

In [41]:
x_test

f1  f2
8  41  33
2   6  85

In [42]:
y_train

0    27
4    29
9     5
3    46
5     2
7    53
6    22
1    70
Name: f3, dtype: int32

In [43]:
y_test

8    10
2    69
Name: f3, dtype: int32