In [1]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf


C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.enable_eager_execution()

In [3]:
tf.executing_eagerly()

True

In [5]:
x = [[2.]]
m = tf.matmul(x, x)
print("hello, {}".format(m))

hello, [[4.]]


In [6]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [13]:
#Cong matran a voi 1
b = tf.add(a, 1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [14]:
#Nhan 2 mang tran
print(a * b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [94]:
tfe = tf.contrib.eager

In [86]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  max_num = tf.convert_to_tensor(max_num)
  for num in range(max_num.numpy()):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('FizzBuzz')
    elif int(num % 3) == 0:
      print('Fizz')
    elif int(num % 5) == 0:
      print('Buzz')
    else:
      print(num)
    counter += 1
  return counter

In [87]:
class MySimpleLayer(tf.keras.layers.Layer):
  def __init__(self, output_units):
    super(MySimpleLayer, self).__init__()
    self.output_units = output_units

  def build(self, input_shape):
    # The build method gets called the first time your layer is used.
    # Creating variables on build() allows you to make their shape depend
    # on the input shape and hence removes the need for the user to specify
    # full shapes. It is possible to create variables during __init__() if
    # you already know their full shapes.
    self.kernel = self.add_variable(
      "kernel", [input_shape[-1], self.output_units])

  def call(self, input):
    # Override call() instead of __call__ so we can perform some bookkeeping.
    return tf.matmul(input, self.kernel)

In [88]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, input_shape=(784,)),  # must declare input shape
  tf.keras.layers.Dense(10)
])

In [89]:
class MNISTModel(tf.keras.Model):
  def __init__(self):
    super(MNISTModel, self).__init__()
    self.dense1 = tf.keras.layers.Dense(units=10)
    self.dense2 = tf.keras.layers.Dense(units=10)

  def call(self, input):
    """Run the model."""
    result = self.dense1(input)
    result = self.dense2(result)
    result = self.dense2(result)  # reuse variables from dense2 layer
    return result

model = MNISTModel()

In [90]:
w = tfe.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = w * w

grad = tape.gradient(loss, w)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


In [91]:
NUM_EXAMPLES = 1000
training_inputs = tf.random_normal([NUM_EXAMPLES])
noise = tf.random_normal([NUM_EXAMPLES])
training_outputs = training_inputs * 3 + 2 + noise

def prediction(input, weight, bias):
  return input * weight + bias

# A loss function using mean-squared error
def loss(weights, biases):
  error = prediction(training_inputs, weights, biases) - training_outputs
  return tf.reduce_mean(tf.square(error))

# Return the derivative of loss with respect to weight and bias
def grad(weights, biases):
  with tf.GradientTape() as tape:
    loss_value = loss(weights, biases)
  return tape.gradient(loss_value, [weights, biases])

train_steps = 200
learning_rate = 0.01
# Start with arbitrary values for W and B on the same batch of data
W = tfe.Variable(5.)
B = tfe.Variable(10.)

print("Initial loss: {:.3f}".format(loss(W, B)))

for i in range(train_steps):
  dW, dB = grad(W, B)
  W.assign_sub(dW * learning_rate)
  B.assign_sub(dB * learning_rate)
  if i % 20 == 0:
    print("Loss at step {:03d}: {:.3f}".format(i, loss(W, B)))

print("Final loss: {:.3f}".format(loss(W, B)))
print("W = {}, B = {}".format(W.numpy(), B.numpy()))

Initial loss: 69.190
Loss at step 000: 66.488
Loss at step 020: 30.176
Loss at step 040: 13.995
Loss at step 060: 6.784
Loss at step 080: 3.571
Loss at step 100: 2.139
Loss at step 120: 1.501
Loss at step 140: 1.216
Loss at step 160: 1.090
Loss at step 180: 1.033
Final loss: 1.009
W = 3.0199620723724365, B = 2.132906675338745


In [96]:
import numpy as np

In [18]:
c = np.multiply(a, b)
print(c)

[[ 2  6]
 [12 20]]


In [19]:
print(a.numpy())

[[1 2]
 [3 4]]


# Linear Regression using Eager

In [21]:
x_data=np.random.random((10000,2))

In [22]:
x_data

array([[0.2520163 , 0.15640403],
       [0.98637288, 0.61194648],
       [0.57493879, 0.50010262],
       ...,
       [0.53894955, 0.79082317],
       [0.5687879 , 0.5220626 ],
       [0.19887645, 0.42466909]])

In [23]:
sample_weight=np.array([[3,4]])
sample_weight

array([[3, 4]])

In [24]:
y_data=np.matmul(x_data,sample_weight.transpose())

In [26]:
y_data

array([[1.38166501],
       [5.40690454],
       [3.72522687],
       ...,
       [4.78014135],
       [3.7946141 ],
       [2.29530572]])

In [27]:
y_data.shape

(10000, 1)

In [31]:
y_data=np.add(y_data,np.random.uniform(-0.5,0.5))

In [32]:
y_data

array([[1.85182501],
       [5.87706455],
       [4.19538688],
       ...,
       [5.25030136],
       [4.26477411],
       [2.76546573]])

In [58]:
from sklearn.model_selection import train_test_split



In [59]:
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2)

In [60]:
x_train.shape

(8000, 2)

In [76]:
tfe=tf.contrib.eager

In [77]:
W=tfe.Variable([1.0,1.0])
b=tfe.Variable(np.random.uniform(-0.2,0.2))

In [78]:
#Tinh toan ham mat mat
def linear_regression(inputs):
    return tf.matmul(input,W,transpose_b=True)
#Loss function
def loss_function(model_function,inputs,lables):
    return tf.reduce_min(tf.square(model_function(inputs)-lables))


In [79]:
learning_rate=0.01
number_steps=1000

In [80]:
optimizer=tf.train.GradientDescentOptimizer(learning_rate=learning_rate)

In [81]:
grad=tfe.implicit_gradients(loss_function)

In [85]:
# trainning model
for step in range(number_steps):
    optimizer.apply_gradients(grad(linear_regression, np.float32(x_train), np.float32(y_train)))
    if(step%100==0):
        train_loss=loss_function(linear_regression, np.float32(x_train), np.float32(y_train))
        test_loss=loss_function(linear_regression, np.float32(x_test), np.float32(y_test))
        print("step {} train_loss ={} test_loss= {}".format(step,train_lost,test_loss))

ValueError: Attempt to convert a value (<bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x000001E08FCF3D68>>) with an unsupported type (<class 'method'>) to a Tensor.

In [103]:
import numpy as np
np.random.rand()

0.5607914443535409

In [100]:
np.random.rand()

0.4336423636798592

In [101]:
np.random.rand()

0.6379421091572496