In [1]:
import tensorflow as tf

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
tf.__version__

'1.10.0'

In [3]:
x1=tf.constant(1,name='constan_x1')
print(x1)
x2=tf.constant(2.,name='constant_x2')
print(x2)

Tensor("constan_x1:0", shape=(), dtype=int32)
Tensor("constant_x2:0", shape=(), dtype=float32)


In [4]:
v1=tf.constant([1,2,3],dtype=tf.int32,name='constant_v1')
print(v1)

Tensor("constant_v1:0", shape=(3,), dtype=int32)


In [5]:
session =tf.Session()
session.run(v1)

array([1, 2, 3])

**Note** tensor có thể là một số thực,số nguyên,chuỗi,ma trận 1D,2D,3D

In [6]:
v2=tf.constant([
    [1,2,3],
    [3,4,5]
],dtype=tf.int32,name='constantv2')
session.run(v2)

array([[1, 2, 3],
       [3, 4, 5]])

In [7]:
v2.eval(session=session)

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
v3=tf.constant([
    [1,2,3],
    [3,4,5]
],dtype=tf.int32,name='constantv2')

y2=v2+v3
session.run(y2)

array([[ 2,  4,  6],
       [ 6,  8, 10]])

## Placeholder
load dữ liệu đầu vào

In [9]:
p1=tf.placeholder(dtype=tf.float32)
p2=tf.placeholder(dtype=tf.float32)

o_add=p1+p2
o_mul=p1*p2
o_dteal=p1**2+p2
print(o_add)

d_value={
    p1:20,
    p2:10
}
session.run(o_add,feed_dict=d_value)

Tensor("add_1:0", dtype=float32)


30.0

In [10]:
session.run([o_add,o_mul,o_dteal],feed_dict=d_value)

[30.0, 200.0, 410.0]

In [11]:
var_1=tf.Variable(name='1',initial_value=10)
var_2=tf.Variable(name='1',initial_value=30)

session.run(var_1.initializer)

In [12]:
tf.global_variables_initializer().run(session=session)
session.run(var_1)

10

In [13]:
session.run(var_2)

30